name: Deploy Wine Model Endpoint

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install boto3
      run: pip install boto3

    - name: Deploy model
      run: python scripts/deploy_latest_model.py
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SAGEMAKER_ROLE_ARN: ${{ secrets.SAGEMAKER_ROLE_ARN }}
